<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Game;

use Atlas\Table\Table;

/**
 * @method GameRow|null fetchRow($primaryVal)
 * @method GameRow[] fetchRows(array $primaryVals)
 * @method GameTableSelect select(array $whereEquals = [])
 * @method GameRow newRow(array $cols = [])
 * @method GameRow newSelectedRow(array $cols)
 */
class GameTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'game';

    const COLUMNS = [
        'game_id' => array (
  'name' => 'game_id',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'name' => array (
  'name' => 'name',
  'type' => 'varchar',
  'size' => 50,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'description' => array (
  'name' => 'description',
  'type' => 'text',
  'size' => 65535,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'created_at' => array (
  'name' => 'created_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'updated_at' => array (
  'name' => 'updated_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'game_id',
        'name',
        'description',
        'created_at',
        'updated_at',
    ];

    const COLUMN_DEFAULTS = [
        'game_id' => null,
        'name' => null,
        'description' => null,
        'created_at' => null,
        'updated_at' => null,
    ];

    const PRIMARY_KEY = [
        'game_id',
    ];

    const AUTOINC_COLUMN = 'game_id';

    const AUTOINC_SEQUENCE = null;
}
