<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Game;

/**
 * @property mixed $game_id int(10,0) NOT NULL
 * @property mixed $name varchar(50) NOT NULL
 * @property mixed $description text(65535) NOT NULL
 * @property mixed $created_at timestamp NOT NULL
 * @property mixed $updated_at timestamp NOT NULL
 */
trait GameFields
{
}
